### ISSUE TITLE
Translate Documentation ?

### ISSUE THREAD

**Issue by iooner** [caddyserver/caddyserver.com#101]
Translate documentation to bring Caddy at more users.
I can handle the french translation.

**Comment by mholt** [comment]
@iooner That would be fantastic -- but hold up just a little bit because Caddy's getting a new website in a while and I'm revamping the docs. When that's done, I would love to have your help!

(There will be fewer docs with the new site because 3rd-party plugin docs will be hosted with the plugins, not on the Caddy website, in full at least.)
