### ISSUE TITLE
discussion on proxy page

### ISSUE THREAD

**Issue by jungle-boogie** [caddyserver/caddyserver.com#22]
continuation from this: https://github.com/mholt/caddy/issues/365

I don't want to overwhelm the reader at all. If the docs get too long, people will think Caddy is too complex and similar enough to nginx and apache not to try caddy.

My confusion came from this page:
https://caddyserver.com/docs/placeholders

    These placeholders only work on directives that support them. 
    Check the documentation for your directive to see if placeholders are supported.

On the proxy page, I don't see the ones you mentioned like `{remote}` and `{host}`. The proxy page DOES link to the placeholders page, so perhaps by doing so, this is stating all the request placeholders are acceptable.

While on the placeholder page, what do you think about linking (or simply mentioning) where response placeholders are used?

    These values are obtained from the response, and are only implemented with some directives.
    Make sure your directive supports response placeholders before attempting to use them.

Change some from to x,y,z, etc

**Comment by mholt** [comment]
The problem is that directives change and there are a lot of them (and will be even more as people write add-ons for Caddy), so maintaining that list in two places is a maintenance burden and can become unwieldy. Since the proxy page does link to the placeholders page and specifies that it supports *request* placeholders, I'm OK with leaving it as-is... at least, rather than maintaining a separate list of directives.
