### ISSUE TITLE
IPv6 support for caddyserver.com?

### ISSUE THREAD

**Issue by k0nsl** [caddyserver/caddyserver.com#39]
Hello,

Any plans to add support for IPv6 at `caddyserver.com`? It would make automated installs on IPv6-only servers / virtual private servers a lot easier.

Thanks!

**Comment by mholt** [comment]
I believe IPv6 is already enabled.

I have access to two ISPs -- Google Fiber is one, which is IPv6-enabled, and the local trash ISP is the other one, which does not have IPv6. Loading caddyserver.com over IPv6 on my Google Fiber connection works.

Is it not loading for you?

**Comment by k0nsl** [comment]
Hi @mholt 

I tried to ping `caddyserver.com` from four different hosts via IPv6 and they all return `unknown host`.

**Comment by mholt** [comment]
Can you share more details? I'm able to connect to the server using IPv6.

**Comment by k0nsl** [comment]
I'm not sure what to share. I can't connect via IPv6 from providers such as RamNode, HostHatch, Dacentec/CentriLogic, Makonix along with two residential ISPs here in Scandinavia.

**Comment by mholt** [comment]
I just remembered I recently switched DNS providers because our old one (DigitalOcean) had an outage (via CloudFlare). So I got the site set up with a new DNS provider and a secondary one, but apparently forgot to create the AAAA record.

So I just did that, and I think that's all it'll take for IPv6 to work. Let me know if you still have trouble.

**Comment by k0nsl** [comment]
Hi @mholt 

Yes, it all works fine now. Thank you.
