### ISSUE TITLE
Installer script bug

### ISSUE THREAD

**Issue by MSF-Jarvis** [caddyserver/caddyserver.com#49]
@mholt, this is the transcript of my terminal 
```
curl https://getcaddy.com/ | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--  0     0    0     0    0     0      0      0 --:--  0     0    0     0    0     0      0      0 --:--100  4204  100  4204    0     0   2640      0  0:00:01  0:00:01 --:--:--  2655
Downloading Caddy for linux/arm...
https://caddyserver.com/download/build?os=linux&arch=arm&arm=7&features=
curl: (23) Failed writing body (0 != 3162)
```

Dunno who to blame.

**Comment by MSF-Jarvis** [comment]
I'm on Android 6.0.1, stock, rooted using Termux from the Play Store

**Comment by mholt** [comment]
Okay, thanks for the report; I see the same. This appears to be because /tmp does not exist. In Termux, the file system is read-only, so we cannot create the folder. The script downloads caddy to /tmp so it can extract it into the $PATH. And looking at that, I see that /usr/local/bin doesn't exist either, but Termux does at least have a $PATH.

The Termux $PATH exists inside $PREFIX which is the 'base' path to Termux's "user space" root of the file system, I guess.

So all we have to do is detect that this is Termux on Android and, if so, use $PREFIX.

Maybe we could even just change all paths to be prefixed with `$PREFIX` so `/tmp` becomes `$PREFIX/tmp` and `/usr/local/bin` becomes `$PREFIX/usr/local/bin`.

That should fix it. Any opposed?

**Comment by mholt** [comment]
Actually, Termux doesn't have a `$PREFIX/usr/local/bin` and it's definitely not in $PATH, so we could just change the install path from `/usr/local/bin` to `/usr/bin` -- and if we did that for everyone it'd keep things consistent. Is that good?

**Comment by MSF-Jarvis** [comment]
@mholt, this seems a fair enough solution. Just make sure the backup part of the script looks for existing caddy installations in *both* `/usr/local/bin` and `/usr/bin` from now on.

**Comment by mholt** [comment]
Okay. I'll just use /usr/bin since nobody really knows about getcaddy.com yet. (Not "official" quite yet, still an experiment.)

**Comment by MSF-Jarvis** [comment]
How do you think my (website)[https:// msfjarvis.me/] got it's caddy
installation? *THE SCRIPT*

**Comment by mholt** [comment]
You're one of very few. :smile:

**Comment by mholt** [comment]
Works now! Thanks for the report.

Also created a [new repo](https://github.com/caddyserver/getcaddy.com) for this.
